from fastapi import APIRouter
from typing import List
from models import ProductSchema

router = APIRouter(prefix="/products", tags=["Products"])

# Plant Master Product Catalog
PRODUCTS_STORE: List[dict] = [
    {
        "product_id": "9900010",
        "product_name": "Sweet Curd Cup 400g (S400)",
        "item_code": "9900010",
        "short_code": "S400",
        "category": "Curd",
        "unit": "g",
        "pack_size": 400.0,
        "pack_size_display": "400 g",
        "pieces_per_crate": 15,
        "per_crate_qty": 6.0,
        "per_crate_qty_grams": 6000.0,
        "per_crate_display": "6.0 kg (6000.0 g)",
        "price_per_piece": 55.0,
        "shelf_life": "12 Days",
        "allowed_input_modes": ["Pieces", "Crates", "Kg"],
        "target_fat": 3.5,
        "target_snf": 10.0,
        "active": True
    },
    {
        "product_id": "9900026",
        "product_name": "Plain Curd Cup 80g (P80)",
        "item_code": "9900026",
        "short_code": "P80",
        "category": "Curd",
        "unit": "g",
        "pack_size": 80.0,
        "pack_size_display": "80 g",
        "pieces_per_crate": 60,
        "per_crate_qty": 4.8,
        "per_crate_qty_grams": 4800.0,
        "per_crate_display": "4.8 kg (4800.0 g)",
        "price_per_piece": 15.0,
        "shelf_life": "12 Days",
        "allowed_input_modes": ["Pieces", "Crates", "Kg"],
        "target_fat": 3.2,
        "target_snf": 9.0,
        "active": True
    },
    {
        "product_id": "9900013",
        "product_name": "Plain Curd Cup 400g (P400)",
        "item_code": "9900013",
        "short_code": "P400",
        "category": "Curd",
        "unit": "g",
        "pack_size": 400.0,
        "pack_size_display": "400 g",
        "pieces_per_crate": 15,
        "per_crate_qty": 6.0,
        "per_crate_qty_grams": 6000.0,
        "per_crate_display": "6.0 kg (6000.0 g)",
        "price_per_piece": 55.0,
        "shelf_life": "12 Days",
        "allowed_input_modes": ["Pieces", "Crates", "Kg"],
        "target_fat": 3.2,
        "target_snf": 9.0,
        "active": True
    },
    {
        "product_id": "9900007",
        "product_name": "Purabi Lassi 200 ml (PL200)",
        "item_code": "9900007",
        "short_code": "PL200",
        "category": "Fermented",
        "unit": "ml",
        "pack_size": 200.0,
        "pack_size_display": "200 ml",
        "pieces_per_crate": 30,
        "per_crate_qty": 6.0,
        "per_crate_qty_grams": 6000.0,
        "per_crate_display": "6.0 L (6000.0 ml)",
        "price_per_piece": 20.0,
        "shelf_life": "7 Days",
        "allowed_input_modes": ["Pieces", "Crates", "Litres"],
        "target_fat": 2.5,
        "target_snf": 9.0,
        "active": True
    },
    {
        "product_id": "CP400",
        "product_name": "Curd Pouch 400 g (CP400)",
        "item_code": "NA",
        "short_code": "CP400",
        "category": "Curd",
        "unit": "g",
        "pack_size": 400.0,
        "pack_size_display": "400 g",
        "pieces_per_crate": 30,
        "per_crate_qty": 12.0,
        "per_crate_qty_grams": 12000.0,
        "per_crate_display": "12.0 kg (12000.0 g)",
        "price_per_piece": 35.0,
        "shelf_life": "12 Days",
        "allowed_input_modes": ["Pieces", "Crates", "Kg"],
        "target_fat": 3.2,
        "target_snf": 9.5,
        "active": True
    },
    {
        "product_id": "CP1000",
        "product_name": "Curd Pouch 1 kg (CP1000)",
        "item_code": "NA",
        "short_code": "CP1000",
        "category": "Curd",
        "unit": "g",
        "pack_size": 1000.0,
        "pack_size_display": "1 kg (1000 g)",
        "pieces_per_crate": 12,
        "per_crate_qty": 12.0,
        "per_crate_qty_grams": 12000.0,
        "per_crate_display": "12.0 kg (12000.0 g)",
        "price_per_piece": 75.0,
        "shelf_life": "12 Days",
        "allowed_input_modes": ["Pieces", "Crates", "Kg"],
        "target_fat": 3.2,
        "target_snf": 9.5,
        "active": True
    },
    {
        "product_id": "PRD-001",
        "product_name": "Purabi Plus Milk 500 ml",
        "item_code": "9900001",
        "short_code": "PPM500",
        "category": "Milk",
        "unit": "ml",
        "pack_size": 500.0,
        "pack_size_display": "500 ml",
        "pieces_per_crate": 20,
        "per_crate_qty": 10.0,
        "per_crate_qty_grams": 10000.0,
        "per_crate_display": "10.0 L (10000.0 ml)",
        "price_per_piece": 28.0,
        "shelf_life": "2 Days",
        "allowed_input_modes": ["Pieces", "Crates", "Litres"],
        "target_fat": 4.5,
        "target_snf": 8.5,
        "active": True
    },
    {
        "product_id": "PRD-002",
        "product_name": "Purabi Plus Milk 250 ml",
        "item_code": "9900002",
        "short_code": "PPM250",
        "category": "Milk",
        "unit": "ml",
        "pack_size": 250.0,
        "pack_size_display": "250 ml",
        "pieces_per_crate": 40,
        "per_crate_qty": 10.0,
        "per_crate_qty_grams": 10000.0,
        "per_crate_display": "10.0 L (10000.0 ml)",
        "price_per_piece": 15.0,
        "shelf_life": "2 Days",
        "allowed_input_modes": ["Pieces", "Crates", "Litres"],
        "target_fat": 4.5,
        "target_snf": 8.5,
        "active": True
    },
    {
        "product_id": "PRD-006",
        "product_name": "Toned Milk 500 ml",
        "item_code": "9900003",
        "short_code": "TM500",
        "category": "Milk",
        "unit": "ml",
        "pack_size": 500.0,
        "pack_size_display": "500 ml",
        "pieces_per_crate": 20,
        "per_crate_qty": 10.0,
        "per_crate_qty_grams": 10000.0,
        "per_crate_display": "10.0 L (10000.0 ml)",
        "price_per_piece": 26.0,
        "shelf_life": "2 Days",
        "allowed_input_modes": ["Pieces", "Crates", "Litres"],
        "target_fat": 3.0,
        "target_snf": 8.5,
        "active": True
    },
    {
        "product_id": "PRD-008",
        "product_name": "Full Cream Milk 1 L",
        "item_code": "9900004",
        "short_code": "FCM1000",
        "category": "Milk",
        "unit": "ml",
        "pack_size": 1000.0,
        "pack_size_display": "1000 ml (1 L)",
        "pieces_per_crate": 12,
        "per_crate_qty": 12.0,
        "per_crate_qty_grams": 12000.0,
        "per_crate_display": "12.0 L (12000.0 ml)",
        "price_per_piece": 66.0,
        "shelf_life": "2 Days",
        "allowed_input_modes": ["Pieces", "Crates", "Litres"],
        "target_fat": 6.0,
        "target_snf": 9.0,
        "active": True
    }
]

@router.get("", response_model=List[ProductSchema])
def get_products():
    return PRODUCTS_STORE

@router.post("", response_model=ProductSchema)
def create_product(product: ProductSchema):
    PRODUCTS_STORE.append(product.model_dump())
    return product
