import '../../models/product_model.dart';

/// Centralized, reusable official products catalog for CASEYA dairy operations.
class DairyProducts {
  static const List<ProductModel> officialProducts = [
    // 1. STD 500 ml
    ProductModel(
      productId: '9900027',
      productName: 'STD 500 ml',
      itemCode: '9900027',
      shortCode: 'STD 500',
      category: 'Milk',
      unit: 'ml',
      packSize: 500,
      packSizeDisplay: '500 ml',
      piecesPerCrate: 24,
      perCrateQty: 12.0,
      perCrateQtyGrams: 12000.0,
      perCrateDisplay: '12.0 L (12000.0 ml)',
      pricePerPiece: 35.0,
      shelfLife: '2 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Litres'],
      targetFat: 4.5,
      targetSnf: 8.5,
    ),

    // 2. STD 250 ml
    ProductModel(
      productId: '9900095',
      productName: 'STD 250 ml',
      itemCode: '9900095',
      shortCode: 'STD 250',
      category: 'Milk',
      unit: 'ml',
      packSize: 250,
      packSizeDisplay: '250 ml',
      piecesPerCrate: 48,
      perCrateQty: 12.0,
      perCrateQtyGrams: 12000.0,
      perCrateDisplay: '12.0 L (12000.0 ml)',
      pricePerPiece: 18.0,
      shelfLife: '2 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Litres'],
      targetFat: 4.5,
      targetSnf: 8.5,
    ),

    // 3. SM+ (Army Milk)
    ProductModel(
      productId: 'SMART500',
      productName: 'SM+ (Army Milk)',
      itemCode: 'NA',
      shortCode: 'SM+',
      category: 'Milk',
      unit: 'ml',
      packSize: 500,
      packSizeDisplay: '500 ml',
      piecesPerCrate: 24,
      perCrateQty: 12.0,
      perCrateQtyGrams: 12000.0,
      perCrateDisplay: '12.0 L (12000.0 ml)',
      pricePerPiece: 0.0,
      priceCustomLabel: 'Defence Supply',
      shelfLife: '2 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Litres'],
      targetFat: 3.0,
      targetSnf: 8.5,
    ),

    // 4. Lassi 200 ml
    ProductModel(
      productId: '9900007',
      productName: 'Lassi 200 ml',
      itemCode: '9900007',
      shortCode: 'Lassi 200',
      category: 'Fermented',
      unit: 'ml',
      packSize: 200,
      packSizeDisplay: '200 ml',
      piecesPerCrate: 30,
      perCrateQty: 6.0,
      perCrateQtyGrams: 6000.0,
      perCrateDisplay: '6.0 L (6000.0 ml)',
      pricePerPiece: 20.0,
      shelfLife: '7 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Litres'],
      targetFat: 2.5,
      targetSnf: 9.0,
    ),

    // 5. Sweet Curd Cup (S80)
    ProductModel(
      productId: '9900025',
      productName: 'Sweet Curd Cup (S80)',
      itemCode: '9900025',
      shortCode: 'S80',
      category: 'Curd',
      unit: 'g',
      packSize: 80,
      packSizeDisplay: '80 g',
      piecesPerCrate: 60,
      perCrateQty: 4.8,
      perCrateQtyGrams: 4800.0,
      perCrateDisplay: '4.8 kg (4800.0 g)',
      pricePerPiece: 15.0,
      shelfLife: '12 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Kg'],
      targetFat: 3.5,
      targetSnf: 10.0,
    ),

    // 6. Sweet Curd Cup (S200)
    ProductModel(
      productId: '9900011',
      productName: 'Sweet Curd Cup (S200)',
      itemCode: '9900011',
      shortCode: 'S200',
      category: 'Curd',
      unit: 'g',
      packSize: 200,
      packSizeDisplay: '200 g',
      piecesPerCrate: 30,
      perCrateQty: 6.0,
      perCrateQtyGrams: 6000.0,
      perCrateDisplay: '6.0 kg (6000.0 g)',
      pricePerPiece: 30.0,
      shelfLife: '12 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Kg'],
      targetFat: 3.5,
      targetSnf: 10.0,
    ),

    // 7. Sweet Curd Cup (S400)
    ProductModel(
      productId: '9900010',
      productName: 'Sweet Curd Cup (S400)',
      itemCode: '9900010',
      shortCode: 'S400',
      category: 'Curd',
      unit: 'g',
      packSize: 400,
      packSizeDisplay: '400 g',
      piecesPerCrate: 15,
      perCrateQty: 6.0,
      perCrateQtyGrams: 6000.0,
      perCrateDisplay: '6.0 kg (6000.0 g)',
      pricePerPiece: 55.0,
      shelfLife: '12 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Kg'],
      targetFat: 3.5,
      targetSnf: 10.0,
    ),

    // 8. Sweet Curd Pouch 400 gm (SCP 400)
    ProductModel(
      productId: 'SCP400',
      productName: 'Sweet Curd Pouch 400 gm (SCP 400)',
      itemCode: 'NA',
      shortCode: 'SCP 400',
      category: 'Curd',
      unit: 'g',
      packSize: 400,
      packSizeDisplay: '400 g',
      piecesPerCrate: 30,
      perCrateQty: 12.0,
      perCrateQtyGrams: 12000.0,
      perCrateDisplay: '12.0 kg (12000.0 g)',
      pricePerPiece: 40.0,
      shelfLife: '12 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Kg'],
      targetFat: 3.5,
      targetSnf: 10.0,
    ),

    // 9. Sweet Curd Pouch 1 kg (SCP1000)
    ProductModel(
      productId: 'SCP1000',
      productName: 'Sweet Curd Pouch 1 kg (SCP1000)',
      itemCode: 'NA',
      shortCode: 'SCP1000',
      category: 'Curd',
      unit: 'g',
      packSize: 1000,
      packSizeDisplay: '1 kg (1000 g)',
      piecesPerCrate: 12,
      perCrateQty: 12.0,
      perCrateQtyGrams: 12000.0,
      perCrateDisplay: '12.0 kg (12000.0 g)',
      pricePerPiece: 90.0,
      shelfLife: '12 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Kg'],
      targetFat: 3.5,
      targetSnf: 10.0,
    ),

    // 10. Plain Curd Cup (P80)
    ProductModel(
      productId: '9900026',
      productName: 'Plain Curd Cup (P80)',
      itemCode: '9900026',
      shortCode: 'P80',
      category: 'Curd',
      unit: 'g',
      packSize: 80,
      packSizeDisplay: '80 g',
      piecesPerCrate: 60,
      perCrateQty: 4.8,
      perCrateQtyGrams: 4800.0,
      perCrateDisplay: '4.8 kg (4800.0 g)',
      pricePerPiece: 15.0,
      shelfLife: '12 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Kg'],
      targetFat: 3.2,
      targetSnf: 9.0,
    ),

    // 11. Plain Curd Cup (P200)
    ProductModel(
      productId: 'P200',
      productName: 'Plain Curd Cup (P200)',
      itemCode: 'NA',
      shortCode: 'P200',
      category: 'Curd',
      unit: 'g',
      packSize: 200,
      packSizeDisplay: '200 g',
      piecesPerCrate: 30,
      perCrateQty: 6.0,
      perCrateQtyGrams: 6000.0,
      perCrateDisplay: '6.0 kg (6000.0 g)',
      pricePerPiece: 30.0,
      shelfLife: '12 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Kg'],
      targetFat: 3.2,
      targetSnf: 9.0,
    ),

    // 12. Plain Curd Cup (P400)
    ProductModel(
      productId: '9900013',
      productName: 'Plain Curd Cup (P400)',
      itemCode: '9900013',
      shortCode: 'P400',
      category: 'Curd',
      unit: 'g',
      packSize: 400,
      packSizeDisplay: '400 g',
      piecesPerCrate: 15,
      perCrateQty: 6.0,
      perCrateQtyGrams: 6000.0,
      perCrateDisplay: '6.0 kg (6000.0 g)',
      pricePerPiece: 55.0,
      shelfLife: '12 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Kg'],
      targetFat: 3.2,
      targetSnf: 9.0,
    ),

    // 13. Plain Curd Pouch 400 gm (PCP 400)
    ProductModel(
      productId: 'PCP400',
      productName: 'Plain Curd Pouch 400 gm (PCP 400)',
      itemCode: 'NA',
      shortCode: 'PCP 400',
      category: 'Curd',
      unit: 'g',
      packSize: 400,
      packSizeDisplay: '400 g',
      piecesPerCrate: 30,
      perCrateQty: 12.0,
      perCrateQtyGrams: 12000.0,
      perCrateDisplay: '12.0 kg (12000.0 g)',
      pricePerPiece: 35.0,
      shelfLife: '12 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Kg'],
      targetFat: 3.2,
      targetSnf: 9.5,
    ),

    // 14. Plain Curd Pouch 1 kg (PCP1000)
    ProductModel(
      productId: 'PCP1000',
      productName: 'Plain Curd Pouch 1 kg (PCP1000)',
      itemCode: 'NA',
      shortCode: 'PCP1000',
      category: 'Curd',
      unit: 'g',
      packSize: 1000,
      packSizeDisplay: '1 kg (1000 g)',
      piecesPerCrate: 12,
      perCrateQty: 12.0,
      perCrateQtyGrams: 12000.0,
      perCrateDisplay: '12.0 kg (12000.0 g)',
      pricePerPiece: 75.0,
      shelfLife: '12 Days',
      allowedInputModes: ['Pieces', 'Crates', 'Kg'],
      targetFat: 3.2,
      targetSnf: 9.5,
    ),
  ];
}
