import '../../models/product_model.dart';

/// Centralized, reusable official products catalog for CASEYA dairy operations.
/// Configured with 29 exact products, pricing, and packaging specifications.
class DairyProducts {
  static const List<ProductModel> officialProducts = [
    // 1. STD 200ml — ₹15 per packet; 60 pieces per crate.
    ProductModel(
      productId: '9900028',
      productName: 'STD 200ml',
      itemCode: '9900028',
      shortCode: 'STD 200',
      category: 'Milk',
      unit: 'ml',
      packSize: 200,
      packSizeDisplay: '200 ml',
      piecesPerCrate: 60,
      perCrateQty: 12.0,
      perCrateQtyGrams: 12000.0,
      perCrateDisplay: '12.0 L (12000.0 ml)',
      pricePerPiece: 15.0,
      individualSaleUnit: 'packet',
      bulkPackingUnit: 'Crates',
      shelfLife: '2 Days',
      allowedInputModes: ['Packets', 'Crates'],
      targetFat: 4.5,
      targetSnf: 8.5,
    ),

    // 2. STD 250ml — ₹18 per packet; 48 pieces per crate.
    ProductModel(
      productId: '9900095',
      productName: 'STD 250ml',
      itemCode: '9900095',
      shortCode: 'STD 250',
      category: 'Milk',
      unit: 'ml',
      packSize: 250,
      packSizeDisplay: '250 ml',
      piecesPerCrate: 48,
      perCrateQty: 12.0,
      perCrateQtyGrams: 12000.0,
      perCrateDisplay: '12.0 L (12000.0 ml)',
      pricePerPiece: 18.0,
      individualSaleUnit: 'packet',
      bulkPackingUnit: 'Crates',
      shelfLife: '2 Days',
      allowedInputModes: ['Packets', 'Crates'],
      targetFat: 4.5,
      targetSnf: 8.5,
    ),

    // 3. STD 500ml — ₹35 per packet; 24 pieces per crate.
    ProductModel(
      productId: '9900027',
      productName: 'STD 500ml',
      itemCode: '9900027',
      shortCode: 'STD 500',
      category: 'Milk',
      unit: 'ml',
      packSize: 500,
      packSizeDisplay: '500 ml',
      piecesPerCrate: 24,
      perCrateQty: 12.0,
      perCrateQtyGrams: 12000.0,
      perCrateDisplay: '12.0 L (12000.0 ml)',
      pricePerPiece: 35.0,
      individualSaleUnit: 'packet',
      bulkPackingUnit: 'Crates',
      shelfLife: '2 Days',
      allowedInputModes: ['Packets', 'Crates'],
      targetFat: 4.5,
      targetSnf: 8.5,
    ),

    // 4. SM+ 500ml — Defence supply; price not specified; 24 pieces per crate.
    ProductModel(
      productId: 'SMART500',
      productName: 'SM+ 500ml',
      itemCode: 'NA',
      shortCode: 'SM+',
      category: 'Milk',
      unit: 'ml',
      packSize: 500,
      packSizeDisplay: '500 ml',
      piecesPerCrate: 24,
      perCrateQty: 12.0,
      perCrateQtyGrams: 12000.0,
      perCrateDisplay: '12.0 L (12000.0 ml)',
      pricePerPiece: 0.0,
      priceCustomLabel: 'Defence Supply',
      individualSaleUnit: 'packet',
      bulkPackingUnit: 'Crates',
      shelfLife: '2 Days',
      allowedInputModes: ['Packets', 'Crates'],
      targetFat: 3.0,
      targetSnf: 8.5,
    ),

    // 5. Lassi — ₹20 per cup; 30 pieces per crate.
    ProductModel(
      productId: '9900007',
      productName: 'Lassi',
      itemCode: '9900007',
      shortCode: 'Lassi',
      category: 'Fermented',
      unit: 'ml',
      packSize: 200,
      packSizeDisplay: '200 ml',
      piecesPerCrate: 30,
      perCrateQty: 6.0,
      perCrateQtyGrams: 6000.0,
      perCrateDisplay: '6.0 L (6000.0 ml)',
      pricePerPiece: 20.0,
      individualSaleUnit: 'cup',
      bulkPackingUnit: 'Crates',
      shelfLife: '7 Days',
      allowedInputModes: ['Cups', 'Crates'],
      targetFat: 2.5,
      targetSnf: 9.0,
    ),

    // 6. S80 — ₹15 per cup; 60 pieces per crate.
    ProductModel(
      productId: '9900025',
      productName: 'S80',
      itemCode: '9900025',
      shortCode: 'S80',
      category: 'Curd',
      unit: 'g',
      packSize: 80,
      packSizeDisplay: '80 g',
      piecesPerCrate: 60,
      perCrateQty: 4.8,
      perCrateQtyGrams: 4800.0,
      perCrateDisplay: '4.8 kg (4800.0 g)',
      pricePerPiece: 15.0,
      individualSaleUnit: 'cup',
      bulkPackingUnit: 'Crates',
      shelfLife: '12 Days',
      allowedInputModes: ['Cups', 'Crates'],
      targetFat: 3.5,
      targetSnf: 10.0,
    ),

    // 7. S200 — ₹30 per cup; 30 pieces per crate.
    ProductModel(
      productId: '9900011',
      productName: 'S200',
      itemCode: '9900011',
      shortCode: 'S200',
      category: 'Curd',
      unit: 'g',
      packSize: 200,
      packSizeDisplay: '200 g',
      piecesPerCrate: 30,
      perCrateQty: 6.0,
      perCrateQtyGrams: 6000.0,
      perCrateDisplay: '6.0 kg (6000.0 g)',
      pricePerPiece: 30.0,
      individualSaleUnit: 'cup',
      bulkPackingUnit: 'Crates',
      shelfLife: '12 Days',
      allowedInputModes: ['Cups', 'Crates'],
      targetFat: 3.5,
      targetSnf: 10.0,
    ),

    // 8. S400 — ₹55 per cup; 15 pieces per crate.
    ProductModel(
      productId: '9900010',
      productName: 'S400',
      itemCode: '9900010',
      shortCode: 'S400',
      category: 'Curd',
      unit: 'g',
      packSize: 400,
      packSizeDisplay: '400 g',
      piecesPerCrate: 15,
      perCrateQty: 6.0,
      perCrateQtyGrams: 6000.0,
      perCrateDisplay: '6.0 kg (6000.0 g)',
      pricePerPiece: 55.0,
      individualSaleUnit: 'cup',
      bulkPackingUnit: 'Crates',
      shelfLife: '12 Days',
      allowedInputModes: ['Cups', 'Crates'],
      targetFat: 3.5,
      targetSnf: 10.0,
    ),

    // 9. Sweet Curd Pouch 400gm — ₹40 per packet; 30 pieces per crate.
    ProductModel(
      productId: 'SCP400',
      productName: 'Sweet Curd Pouch 400gm',
      itemCode: 'SCP400',
      shortCode: 'SCP 400',
      category: 'Curd',
      unit: 'g',
      packSize: 400,
      packSizeDisplay: '400 g',
      piecesPerCrate: 30,
      perCrateQty: 12.0,
      perCrateQtyGrams: 12000.0,
      perCrateDisplay: '12.0 kg (12000.0 g)',
      pricePerPiece: 40.0,
      individualSaleUnit: 'packet',
      bulkPackingUnit: 'Crates',
      shelfLife: '12 Days',
      allowedInputModes: ['Packets', 'Crates'],
      targetFat: 3.5,
      targetSnf: 10.0,
    ),

    // 10. P80 — ₹15 per cup; 60 pieces per crate.
    ProductModel(
      productId: '9900026',
      productName: 'P80',
      itemCode: '9900026',
      shortCode: 'P80',
      category: 'Curd',
      unit: 'g',
      packSize: 80,
      packSizeDisplay: '80 g',
      piecesPerCrate: 60,
      perCrateQty: 4.8,
      perCrateQtyGrams: 4800.0,
      perCrateDisplay: '4.8 kg (4800.0 g)',
      pricePerPiece: 15.0,
      individualSaleUnit: 'cup',
      bulkPackingUnit: 'Crates',
      shelfLife: '12 Days',
      allowedInputModes: ['Cups', 'Crates'],
      targetFat: 3.2,
      targetSnf: 9.0,
    ),

    // 11. P200 — ₹30 per cup; 30 pieces per crate.
    ProductModel(
      productId: 'P200',
      productName: 'P200',
      itemCode: 'P200',
      shortCode: 'P200',
      category: 'Curd',
      unit: 'g',
      packSize: 200,
      packSizeDisplay: '200 g',
      piecesPerCrate: 30,
      perCrateQty: 6.0,
      perCrateQtyGrams: 6000.0,
      perCrateDisplay: '6.0 kg (6000.0 g)',
      pricePerPiece: 30.0,
      individualSaleUnit: 'cup',
      bulkPackingUnit: 'Crates',
      shelfLife: '12 Days',
      allowedInputModes: ['Cups', 'Crates'],
      targetFat: 3.2,
      targetSnf: 9.0,
    ),

    // 12. P400 — ₹55 per cup; 15 pieces per crate.
    ProductModel(
      productId: '9900013',
      productName: 'P400',
      itemCode: '9900013',
      shortCode: 'P400',
      category: 'Curd',
      unit: 'g',
      packSize: 400,
      packSizeDisplay: '400 g',
      piecesPerCrate: 15,
      perCrateQty: 6.0,
      perCrateQtyGrams: 6000.0,
      perCrateDisplay: '6.0 kg (6000.0 g)',
      pricePerPiece: 55.0,
      individualSaleUnit: 'cup',
      bulkPackingUnit: 'Crates',
      shelfLife: '12 Days',
      allowedInputModes: ['Cups', 'Crates'],
      targetFat: 3.2,
      targetSnf: 9.0,
    ),

    // 13. Plain Curd Pouch 400gm — ₹35 per packet; 30 pieces per crate.
    ProductModel(
      productId: 'PCP400',
      productName: 'Plain Curd Pouch 400gm',
      itemCode: 'PCP400',
      shortCode: 'PCP 400',
      category: 'Curd',
      unit: 'g',
      packSize: 400,
      packSizeDisplay: '400 g',
      piecesPerCrate: 30,
      perCrateQty: 12.0,
      perCrateQtyGrams: 12000.0,
      perCrateDisplay: '12.0 kg (12000.0 g)',
      pricePerPiece: 35.0,
      individualSaleUnit: 'packet',
      bulkPackingUnit: 'Crates',
      shelfLife: '12 Days',
      allowedInputModes: ['Packets', 'Crates'],
      targetFat: 3.2,
      targetSnf: 9.5,
    ),

    // 14. Plain Curd Pouch 1kg — ₹75 per packet; crate size not specified.
    ProductModel(
      productId: 'PCP1000',
      productName: 'Plain Curd Pouch 1kg',
      itemCode: 'PCP1000',
      shortCode: 'PCP 1kg',
      category: 'Curd',
      unit: 'g',
      packSize: 1000,
      packSizeDisplay: '1 kg',
      piecesPerCrate: 0, // Crate size not specified
      pricePerPiece: 75.0,
      individualSaleUnit: 'packet',
      bulkPackingUnit: null,
      shelfLife: '12 Days',
      allowedInputModes: ['Packets'],
      targetFat: 3.2,
      targetSnf: 9.5,
    ),

    // 15. UHT 200ml — ₹17.50 per packet; crate size not specified.
    ProductModel(
      productId: 'UHT200',
      productName: 'UHT 200ml',
      itemCode: 'UHT200',
      shortCode: 'UHT 200',
      category: 'Milk',
      unit: 'ml',
      packSize: 200,
      packSizeDisplay: '200 ml',
      piecesPerCrate: 0, // Crate size not specified
      pricePerPiece: 17.50,
      individualSaleUnit: 'packet',
      bulkPackingUnit: null,
      shelfLife: '90 Days',
      allowedInputModes: ['Packets'],
      targetFat: 3.0,
      targetSnf: 8.5,
    ),

    // 16. UHT 1000ml — ₹74 per packet; crate size not specified.
    ProductModel(
      productId: 'UHT1000',
      productName: 'UHT 1000ml',
      itemCode: 'UHT1000',
      shortCode: 'UHT 1000',
      category: 'Milk',
      unit: 'ml',
      packSize: 1000,
      packSizeDisplay: '1000 ml',
      piecesPerCrate: 0, // Crate size not specified
      pricePerPiece: 74.0,
      individualSaleUnit: 'packet',
      bulkPackingUnit: null,
      shelfLife: '90 Days',
      allowedInputModes: ['Packets'],
      targetFat: 3.0,
      targetSnf: 8.5,
    ),

    // 17. Flavoured Milk (Kesar) — ₹25 per bottle; crate size not specified.
    ProductModel(
      productId: 'FM_KESAR',
      productName: 'Flavoured Milk (Kesar)',
      itemCode: 'FM_KESAR',
      shortCode: 'FM Kesar',
      category: 'Flavoured Milk',
      unit: 'ml',
      packSize: 200,
      packSizeDisplay: '200 ml',
      piecesPerCrate: 0,
      pricePerPiece: 25.0,
      individualSaleUnit: 'bottle',
      bulkPackingUnit: null,
      shelfLife: '30 Days',
      allowedInputModes: ['Bottles'],
      targetFat: 1.5,
      targetSnf: 8.5,
    ),

    // 18. Flavoured Milk (Mango) — ₹25 per bottle; crate size not specified.
    ProductModel(
      productId: 'FM_MANGO',
      productName: 'Flavoured Milk (Mango)',
      itemCode: 'FM_MANGO',
      shortCode: 'FM Mango',
      category: 'Flavoured Milk',
      unit: 'ml',
      packSize: 200,
      packSizeDisplay: '200 ml',
      piecesPerCrate: 0,
      pricePerPiece: 25.0,
      individualSaleUnit: 'bottle',
      bulkPackingUnit: null,
      shelfLife: '30 Days',
      allowedInputModes: ['Bottles'],
      targetFat: 1.5,
      targetSnf: 8.5,
    ),

    // 19. Flavoured Milk (Hazelnut) — ₹25 per bottle; crate size not specified.
    ProductModel(
      productId: 'FM_HAZELNUT',
      productName: 'Flavoured Milk (Hazelnut)',
      itemCode: 'FM_HAZELNUT',
      shortCode: 'FM Hazelnut',
      category: 'Flavoured Milk',
      unit: 'ml',
      packSize: 200,
      packSizeDisplay: '200 ml',
      piecesPerCrate: 0,
      pricePerPiece: 25.0,
      individualSaleUnit: 'bottle',
      bulkPackingUnit: null,
      shelfLife: '30 Days',
      allowedInputModes: ['Bottles'],
      targetFat: 1.5,
      targetSnf: 8.5,
    ),

    // 20. Flavoured Milk (Strawberry) — ₹25 per bottle; crate size not specified.
    ProductModel(
      productId: 'FM_STRAWBERRY',
      productName: 'Flavoured Milk (Strawberry)',
      itemCode: 'FM_STRAWBERRY',
      shortCode: 'FM Strawberry',
      category: 'Flavoured Milk',
      unit: 'ml',
      packSize: 200,
      packSizeDisplay: '200 ml',
      piecesPerCrate: 0,
      pricePerPiece: 25.0,
      individualSaleUnit: 'bottle',
      bulkPackingUnit: null,
      shelfLife: '30 Days',
      allowedInputModes: ['Bottles'],
      targetFat: 1.5,
      targetSnf: 8.5,
    ),

    // 21. Paneer — ₹92 per packet; 20 packets per box.
    ProductModel(
      productId: 'PANEER200',
      productName: 'Paneer',
      itemCode: 'PANEER200',
      shortCode: 'Paneer',
      category: 'Paneer',
      unit: 'g',
      packSize: 200,
      packSizeDisplay: '200 g',
      piecesPerCrate: 20, // 20 packets per box
      perCrateQty: 4.0,
      perCrateQtyGrams: 4000.0,
      perCrateDisplay: '4.0 kg (20 packets/box)',
      pricePerPiece: 92.0,
      individualSaleUnit: 'packet',
      bulkPackingUnit: 'Boxes',
      shelfLife: '15 Days',
      allowedInputModes: ['Packets', 'Boxes'],
    ),

    // 22. Kalakaand — ₹140 per packet; packaging size not specified.
    ProductModel(
      productId: 'SWEET_KALAKAAND',
      productName: 'Kalakaand',
      itemCode: 'KALAKAAND',
      shortCode: 'Kalakaand',
      category: 'Sweet',
      unit: 'g',
      packSize: 250,
      packSizeDisplay: '250 g',
      piecesPerCrate: 0,
      pricePerPiece: 140.0,
      individualSaleUnit: 'packet',
      bulkPackingUnit: null,
      shelfLife: '7 Days',
      allowedInputModes: ['Packets'],
    ),

    // 23. Milk Cake — ₹150 per packet; packaging size not specified.
    ProductModel(
      productId: 'SWEET_MILKCAKE',
      productName: 'Milk Cake',
      itemCode: 'MILKCAKE',
      shortCode: 'Milk Cake',
      category: 'Sweet',
      unit: 'g',
      packSize: 250,
      packSizeDisplay: '250 g',
      piecesPerCrate: 0,
      pricePerPiece: 150.0,
      individualSaleUnit: 'packet',
      bulkPackingUnit: null,
      shelfLife: '7 Days',
      allowedInputModes: ['Packets'],
    ),

    // 24. Peda — sold by packet; price not specified.
    ProductModel(
      productId: 'SWEET_PEDA',
      productName: 'Peda',
      itemCode: 'PEDA',
      shortCode: 'Peda',
      category: 'Sweet',
      unit: 'g',
      packSize: 250,
      packSizeDisplay: '250 g',
      piecesPerCrate: 0,
      pricePerPiece: 0.0,
      priceCustomLabel: 'Price Pending',
      individualSaleUnit: 'packet',
      bulkPackingUnit: null,
      shelfLife: '7 Days',
      allowedInputModes: ['Packets'],
    ),

    // 25. Ghee 200gm — ₹20 per bottle; packaging size not specified.
    ProductModel(
      productId: 'GHEE200',
      productName: 'Ghee 200gm',
      itemCode: 'GHEE200',
      shortCode: 'Ghee 200g',
      category: 'Ghee',
      unit: 'g',
      packSize: 200,
      packSizeDisplay: '200 g',
      piecesPerCrate: 0,
      pricePerPiece: 20.0,
      individualSaleUnit: 'bottle',
      bulkPackingUnit: null,
      shelfLife: '180 Days',
      allowedInputModes: ['Bottles'],
    ),

    // 26. Ghee 500gm — ₹420 per bottle; packaging size not specified.
    ProductModel(
      productId: 'GHEE500',
      productName: 'Ghee 500gm',
      itemCode: 'GHEE500',
      shortCode: 'Ghee 500g',
      category: 'Ghee',
      unit: 'g',
      packSize: 500,
      packSizeDisplay: '500 g',
      piecesPerCrate: 0,
      pricePerPiece: 420.0,
      individualSaleUnit: 'bottle',
      bulkPackingUnit: null,
      shelfLife: '180 Days',
      allowedInputModes: ['Bottles'],
    ),

    // 27. Honey 125gm — ₹100 per bottle; packaging size not specified.
    ProductModel(
      productId: 'HONEY125',
      productName: 'Honey 125gm',
      itemCode: 'HONEY125',
      shortCode: 'Honey 125g',
      category: 'Honey',
      unit: 'g',
      packSize: 125,
      packSizeDisplay: '125 g',
      piecesPerCrate: 0,
      pricePerPiece: 100.0,
      individualSaleUnit: 'bottle',
      bulkPackingUnit: null,
      shelfLife: '365 Days',
      allowedInputModes: ['Bottles'],
    ),

    // 28. Honey 250gm — ₹180 per bottle; packaging size not specified.
    ProductModel(
      productId: 'HONEY250',
      productName: 'Honey 250gm',
      itemCode: 'HONEY250',
      shortCode: 'Honey 250g',
      category: 'Honey',
      unit: 'g',
      packSize: 250,
      packSizeDisplay: '250 g',
      piecesPerCrate: 0,
      pricePerPiece: 180.0,
      individualSaleUnit: 'bottle',
      bulkPackingUnit: null,
      shelfLife: '365 Days',
      allowedInputModes: ['Bottles'],
    ),

    // 29. Honey 500gm — ₹330 per bottle; packaging size not specified.
    ProductModel(
      productId: 'HONEY500',
      productName: 'Honey 500gm',
      itemCode: 'HONEY500',
      shortCode: 'Honey 500g',
      category: 'Honey',
      unit: 'g',
      packSize: 500,
      packSizeDisplay: '500 g',
      piecesPerCrate: 0,
      pricePerPiece: 330.0,
      individualSaleUnit: 'bottle',
      bulkPackingUnit: null,
      shelfLife: '365 Days',
      allowedInputModes: ['Bottles'],
    ),
  ];
}
